In [13]:
import pandas as pd

from sklearn.naive_bayes import BernoulliNB

from sklearn.model_selection import train_test_split

# accuracy
from sklearn.metrics import accuracy_score

In [14]:
df=pd.read_csv('/content/phishing_website_bernoulli_nb_3000.csv')
df

,HTTPS,IPAddress_URL,URL_Shortener,Suspicious_Word,Many_Subdomains,Popup,External_Redirect,Result
0,1,0,0,0,0,0,0,0
1,0,0,0,0,1,0,0,0
2,1,0,0,0,0,1,0,0
3,1,0,0,0,0,0,0,0
4,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...
2995,1,0,0,0,0,0,0,0
2996,1,0,0,0,0,0,0,0
2997,1,0,0,0,0,0,0,0
2998,1,0,1,1,1,0,0,1
2999,1,0,0,0,1,0,0,1

In [15]:
df.head()

,HTTPS,IPAddress_URL,URL_Shortener,Suspicious_Word,Many_Subdomains,Popup,External_Redirect,Result
0,1,0,0,0,0,0,0,0
1,0,0,0,0,1,0,0,0
2,1,0,0,0,0,1,0,0
3,1,0,0,0,0,0,0,0
4,1,0,0,0,1,0,0,0

In [16]:
df.tail()

,HTTPS,IPAddress_URL,URL_Shortener,Suspicious_Word,Many_Subdomains,Popup,External_Redirect,Result
2995,1,0,0,0,0,0,0,0
2996,1,0,0,0,0,0,0,0
2997,1,0,0,0,0,0,0,0
2998,1,0,1,1,1,0,0,1
2999,1,0,0,0,1,0,0,1

In [17]:
df.describe()

,HTTPS,IPAddress_URL,URL_Shortener,Suspicious_Word,Many_Subdomains,Popup,External_Redirect,Result
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,0.660667,0.307667,0.295000,0.383667,0.309333,0.330333,0.287000,0.498000
std,0.473562,0.461605,0.456119,0.486359,0.462296,0.470412,0.452437,0.500079
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [18]:
df.columns

Index(['HTTPS', 'IPAddress_URL', 'URL_Shortener', 'Suspicious_Word',
       'Many_Subdomains', 'Popup', 'External_Redirect', 'Result'],
      dtype='object')

In [19]:
x=df[['HTTPS', 'IPAddress_URL', 'URL_Shortener', 'Suspicious_Word',
       'Many_Subdomains', 'Popup', 'External_Redirect']]
y=df['Result']

In [20]:
# train and test split
x_train,x_test,y_train,y_test=train_test_split(x,y)
model=BernoulliNB()
model.fit(x_train,y_train)

BernoulliNB()

In [21]:
# accuracy
y_pred=model.predict(x_test)
acc=accuracy_score(y_test,y_pred)

print("Accuracy:",acc)

Accuracy: 0.948

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   HTTPS              3000 non-null   int64
 1   IPAddress_URL      3000 non-null   int64
 2   URL_Shortener      3000 non-null   int64
 3   Suspicious_Word    3000 non-null   int64
 4   Many_Subdomains    3000 non-null   int64
 5   Popup              3000 non-null   int64
 6   External_Redirect  3000 non-null   int64
 7   Result             3000 non-null   int64
dtypes: int64(8)
memory usage: 187.6 KB

In [25]:
#user input
https=int(input("Enter HTTPS:"))
ip=int(input("Enter IPAddress_URL:"))
url=int(input("Enter URL_Shortener:"))
Suspicious_Word=int(input("Enter Suspicious_Word:"))
Many_Subdomains=int(input("Enter Many_Subdomains:"))
Popup=int(input("Enter Popup:"))
External_Redirect=int(input("Enter External_Redirect:"))
user=model.predict([[https,ip,url,Suspicious_Word,Many_Subdomains,Popup,External_Redirect]])
if user==1:
  print("Phishing Website")
else:
  print("Legitimate Website")

Enter HTTPS:1
Enter IPAddress_URL:1
Enter URL_Shortener:1
Enter Suspicious_Word:1
Enter Many_Subdomains:1
Enter Popup:1
Enter External_Redirect:1
Phishing Website

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(