In [2]:
##stock market prediction
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB

from sklearn.preprocessing import LabelEncoder

In [3]:
df=pd.read_csv('/content/stock_market_gaussian_nb_5000.csv')
df

,Date,Open,High,Low,Close,Volume,MA_5,MA_10,RSI_14,Daily_Return_Pct,Volatility_10D_Pct,Target
0,2005-08-25,166.22,167.59,165.48,165.79,3036843,165.69,164.14,66.40,-0.2167,0.7870,DOWN
1,2005-08-26,164.67,165.17,163.26,164.21,3355689,165.35,164.57,58.95,-0.9530,0.6917,DOWN
2,2005-08-29,164.27,165.09,161.74,162.82,2777993,164.84,164.76,53.29,-0.8465,0.7591,DOWN
3,2005-08-30,163.28,163.57,160.87,161.18,3497782,164.03,164.63,47.49,-1.0072,0.7718,DOWN
4,2005-08-31,159.87,161.41,159.49,160.21,3422665,162.84,164.17,44.41,-0.6018,0.5905,DOWN
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,2025-07-01,131.04,133.12,130.04,132.89,5603677,130.43,128.95,80.43,1.4427,0.6493,UP
4996,2025-07-02,133.47,135.02,133.42,134.52,4941619,131.46,129.84,83.31,1.2266,0.6439,UP
4997,2025-07-03,134.75,135.61,134.51,134.88,5254107,132.67,130.71,83.87,0.2676,0.6492,UP
4998,2025-07-07,135.36,136.11,134.11,135.76,4166166,133.81,131.58,85.19,0.6524,0.6477,DOWN
4999,2025-07-08,135.18,135.80,134.82,135.67,3751865,134.74,132.28,84.43,-0.0663,0.6496,DOWN

In [4]:
df.head()

,Date,Open,High,Low,Close,Volume,MA_5,MA_10,RSI_14,Daily_Return_Pct,Volatility_10D_Pct,Target
0,2005-08-25,166.22,167.59,165.48,165.79,3036843,165.69,164.14,66.40,-0.2167,0.7870,DOWN
1,2005-08-26,164.67,165.17,163.26,164.21,3355689,165.35,164.57,58.95,-0.9530,0.6917,DOWN
2,2005-08-29,164.27,165.09,161.74,162.82,2777993,164.84,164.76,53.29,-0.8465,0.7591,DOWN
3,2005-08-30,163.28,163.57,160.87,161.18,3497782,164.03,164.63,47.49,-1.0072,0.7718,DOWN
4,2005-08-31,159.87,161.41,159.49,160.21,3422665,162.84,164.17,44.41,-0.6018,0.5905,DOWN

In [5]:
df.tail()

,Date,Open,High,Low,Close,Volume,MA_5,MA_10,RSI_14,Daily_Return_Pct,Volatility_10D_Pct,Target
4995,2025-07-01,131.04,133.12,130.04,132.89,5603677,130.43,128.95,80.43,1.4427,0.6493,UP
4996,2025-07-02,133.47,135.02,133.42,134.52,4941619,131.46,129.84,83.31,1.2266,0.6439,UP
4997,2025-07-03,134.75,135.61,134.51,134.88,5254107,132.67,130.71,83.87,0.2676,0.6492,UP
4998,2025-07-07,135.36,136.11,134.11,135.76,4166166,133.81,131.58,85.19,0.6524,0.6477,DOWN
4999,2025-07-08,135.18,135.80,134.82,135.67,3751865,134.74,132.28,84.43,-0.0663,0.6496,DOWN

In [6]:
df.describe()

,Open,High,Low,Close,Volume,MA_5,MA_10,RSI_14,Daily_Return_Pct,Volatility_10D_Pct
count,5000.000000,5000.000000,5000.000000,5000.000000,5.000000e+03,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,150.267586,151.261498,149.256242,150.261470,4.301417e+06,150.273590,150.289404,49.526870,-0.001156,0.606472
std,20.975631,21.101360,20.832732,20.971272,9.665285e+05,20.923685,20.823882,21.422104,0.761565,0.186000
min,101.650000,103.240000,101.580000,102.250000,1.575000e+06,102.990000,103.930000,2.840000,-2.517400,0.171900
25%,133.717500,134.767500,132.897500,133.787500,3.637963e+06,133.930000,134.027500,32.625000,-0.528250,0.473400
50%,150.115000,151.100000,149.040000,150.030000,4.242395e+06,150.065000,150.020000,49.260000,-0.014250,0.584200
75%,162.535000,163.635000,161.432500,162.462500,4.921652e+06,162.522500,162.460000,65.852500,0.518425,0.710100
max,230.940000,232.420000,229.520000,231.140000,8.034870e+06,229.700000,228.160000,96.980000,2.804600,1.755200

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                5000 non-null   object
 1   Open                5000 non-null   float64
 2   High                5000 non-null   float64
 3   Low                 5000 non-null   float64
 4   Close               5000 non-null   float64
 5   Volume              5000 non-null   int64
 6   MA_5                5000 non-null   float64
 7   MA_10               5000 non-null   float64
 8   RSI_14              5000 non-null   float64
 9   Daily_Return_Pct    5000 non-null   float64
 10  Volatility_10D_Pct  5000 non-null   float64
 11  Target              5000 non-null   object
dtypes: float64(9), int64(1), object(2)
memory usage: 468.9+ KB

In [8]:
xx=df[['Open', 'High', 'Low', 'Close', 'Volume']]
x=xx

In [9]:
y=df['Target']

In [10]:
m=GaussianNB()
le=LabelEncoder()
yy=le.fit_transform(y)

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,yy,test_size=0.2,random_state=42)

In [12]:
m.fit(x_train,y_train)

GaussianNB()

In [13]:
ypredict=m.predict(x_test)

In [18]:
acc=accuracy_score(y_test,ypredict)
acc*100

86.2

In [28]:
open=float(input('enter open value'))
high=float(input('enter high value'))
low=float(input('enter low value'))
close=float(input('enter close value'))
volume=float(input('enter volume value'))
user=pd.DataFrame({'Open':[open],
                   'High':[high],
                   'Low':[low],
                   'Close':[close],
                   'Volume':[volume]})
p=m.predict(user)
if p[0]==0:
  print('down')
else:
  print('up')

enter open value401200
enter high value402000
enter low value396500
enter close value398000
enter volume value185000
down