In [74]:
#credictcard scam detection with using desicion tree
import pandas  as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score,mean_squared_error

In [3]:
df=pd.read_csv('/content/delivery_time_prediction_3000_rows.csv')
df

,From_City,To_City,Distance_km,Dispatch_Date,Delivery_Days,Expected_Delivery_Date
0,Salem,Kochi,365,2025-12-26,3,2025-12-29
1,Mumbai,Hyderabad,695,2026-02-26,2,2026-02-28
2,Hyderabad,Trichy,931,2026-09-19,4,2026-09-23
3,Trichy,Madurai,137,2026-04-27,1,2026-04-28
4,Trichy,Coimbatore,221,2025-05-16,1,2025-05-17
...,...,...,...,...,...,...
2995,Hyderabad,Coimbatore,1015,2025-04-09,3,2025-04-12
2996,Madurai,Salem,231,2026-08-13,3,2026-08-16
2997,Madurai,Bengaluru,432,2025-09-14,3,2025-09-17
2998,Trichy,Madurai,133,2026-06-14,3,2026-06-17
2999,Hyderabad,Bengaluru,574,2025-08-01,4,2025-08-05

In [4]:
df.head()

,From_City,To_City,Distance_km,Dispatch_Date,Delivery_Days,Expected_Delivery_Date
0,Salem,Kochi,365,2025-12-26,3,2025-12-29
1,Mumbai,Hyderabad,695,2026-02-26,2,2026-02-28
2,Hyderabad,Trichy,931,2026-09-19,4,2026-09-23
3,Trichy,Madurai,137,2026-04-27,1,2026-04-28
4,Trichy,Coimbatore,221,2025-05-16,1,2025-05-17

In [5]:
df.tail()

,From_City,To_City,Distance_km,Dispatch_Date,Delivery_Days,Expected_Delivery_Date
2995,Hyderabad,Coimbatore,1015,2025-04-09,3,2025-04-12
2996,Madurai,Salem,231,2026-08-13,3,2026-08-16
2997,Madurai,Bengaluru,432,2025-09-14,3,2025-09-17
2998,Trichy,Madurai,133,2026-06-14,3,2026-06-17
2999,Hyderabad,Bengaluru,574,2025-08-01,4,2025-08-05

In [52]:
model=DecisionTreeRegressor(max_depth=8,min_samples_leaf=5,random_state=42)

In [53]:
le=LabelEncoder()

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   From_City               3000 non-null   object
 1   To_City                 3000 non-null   object
 2   Distance_km             3000 non-null   int64
 3   Dispatch_Date           3000 non-null   object
 4   Delivery_Days           3000 non-null   int64
 5   Expected_Delivery_Date  3000 non-null   object
 6   a                       3000 non-null   int64
 7   b                       3000 non-null   int64
dtypes: int64(4), object(4)
memory usage: 187.6+ KB

In [55]:
df.describe()

       Distance_km  Delivery_Days            a            b
count  3000.000000    3000.000000  3000.000000  3000.000000
mean    700.969333       2.991000     4.499667     4.524000
std     446.058218       1.303132     2.903126     2.912774
min     126.000000       1.000000     0.000000     0.000000
25%     329.750000       2.000000     2.000000     2.000000
50%     564.000000       3.000000     4.000000     5.000000
75%    1141.000000       4.000000     7.000000     7.000000
max    1650.000000       8.000000     9.000000     9.000000

In [56]:
df.values

array([['Salem', 'Kochi', 365, ..., '2025-12-29', 8, 4],
       ['Mumbai', 'Hyderabad', 695, ..., '2026-02-28', 6, 3],
       ['Hyderabad', 'Trichy', 931, ..., '2026-09-23', 3, 9],
       ...,
       ['Madurai', 'Bengaluru', 432, ..., '2025-09-17', 5, 0],
       ['Trichy', 'Madurai', 133, ..., '2026-06-17', 9, 5],
       ['Hyderabad', 'Bengaluru', 574, ..., '2025-08-05', 3, 0]],
      dtype=object)

In [57]:
df['a']=le.fit_transform(df['From_City'])
df['b']=le.fit_transform(df['To_City'])

In [58]:
y=df['Delivery_Days']
x=df[['a','b','Distance_km']]

In [59]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [60]:
model.fit(x_train,y_train)

DecisionTreeRegressor(max_depth=8, min_samples_leaf=5, random_state=42)

In [61]:
y_pred=model.predict(x_test)

In [76]:
r2=r2_score(y_test,y_pred)
print("R2 score:",r2)
mse=mean_squared_error(y_test,y_pred)
print("Mean Squared Error:",mse)

R2 score: 0.564187616273691
Mean Squared Error: 0.7501590137482768

In [51]:
df.columns

Index(['From_City', 'To_City', 'Distance_km', 'Dispatch_Date', 'Delivery_Days',
       'Expected_Delivery_Date', 'a', 'b'],
      dtype='object')

In [77]:
# user inputs

u1=input('From Location: ').strip().title()
u2=input('To Location: ').strip().title()
u3=float(input('Distance:'))
user=pd.DataFrame({'From_City':[u1],
                'To_City':[u2],
                'Distance_km':[u3]})

u1=le.transform(user['From_City'])[0]
u2=le.transform(user['To_City'])[0]
user['a']=u1
user['b']=u2
user=user[['a','b','Distance_km']]
prediction=model.predict(user)[0]
print('Expected Delivery Date:',round(prediction))

From Location: chennai
To Location: hyderabad
Distance:520
Expected Delivery Date: 2