In [18]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,f1_score,precision_score,recall_score

In [19]:
df=pd.read_csv('/content/crop_recommendation_knn_3000_rows.csv')
df

,Sample_ID,N,P,K,Temperature,Humidity,pH,Rainfall,Crop
0,1,106.6,47.6,10.1,30.8,68.6,6.78,112.5,cotton
1,2,41.7,137.3,192.4,22.9,90.4,6.37,55.1,grapes
2,3,108.0,33.1,3.8,22.5,69.1,7.01,95.1,cotton
3,4,24.8,126.1,164.4,25.9,76.7,5.60,37.8,grapes
4,5,97.0,111.8,51.6,27.2,79.8,7.06,97.9,banana
...,...,...,...,...,...,...,...,...,...
2995,2996,137.8,15.3,55.0,31.4,68.4,7.24,44.7,watermelon
2996,2997,39.7,38.6,36.0,28.3,46.5,5.31,127.8,mango
2997,2998,27.1,30.4,36.1,30.0,43.1,5.69,99.3,mango
2998,2999,27.4,53.2,24.9,19.5,29.9,5.47,107.0,kidneybeans
2999,3000,62.0,48.6,16.1,22.0,54.3,7.20,112.8,maize

In [20]:
df.head()

,Sample_ID,N,P,K,Temperature,Humidity,pH,Rainfall,Crop
0,1,106.6,47.6,10.1,30.8,68.6,6.78,112.5,cotton
1,2,41.7,137.3,192.4,22.9,90.4,6.37,55.1,grapes
2,3,108.0,33.1,3.8,22.5,69.1,7.01,95.1,cotton
3,4,24.8,126.1,164.4,25.9,76.7,5.60,37.8,grapes
4,5,97.0,111.8,51.6,27.2,79.8,7.06,97.9,banana

In [21]:
df.tail()

,Sample_ID,N,P,K,Temperature,Humidity,pH,Rainfall,Crop
2995,2996,137.8,15.3,55.0,31.4,68.4,7.24,44.7,watermelon
2996,2997,39.7,38.6,36.0,28.3,46.5,5.31,127.8,mango
2997,2998,27.1,30.4,36.1,30.0,43.1,5.69,99.3,mango
2998,2999,27.4,53.2,24.9,19.5,29.9,5.47,107.0,kidneybeans
2999,3000,62.0,48.6,16.1,22.0,54.3,7.20,112.8,maize

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sample_ID    3000 non-null   int64
 1   N            3000 non-null   float64
 2   P            3000 non-null   float64
 3   K            3000 non-null   float64
 4   Temperature  3000 non-null   float64
 5   Humidity     3000 non-null   float64
 6   pH           3000 non-null   float64
 7   Rainfall     3000 non-null   float64
 8   Crop         3000 non-null   object
dtypes: float64(7), int64(1), object(1)
memory usage: 211.1+ KB

In [23]:
df.describe()

,Sample_ID,N,P,K,Temperature,Humidity,pH,Rainfall
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,1500.500000,60.061033,54.831933,50.439533,24.174767,64.645600,6.411067,96.601267
std,866.169729,37.661837,33.263538,50.423236,4.387075,26.033932,0.683599,45.683810
min,1.000000,1.500000,0.000000,0.000000,9.600000,10.000000,4.360000,11.000000
25%,750.750000,25.200000,28.475000,19.875000,21.000000,47.575000,5.910000,65.875000
50%,1500.500000,53.800000,49.950000,34.300000,24.150000,74.400000,6.380000,87.450000
75%,2250.250000,92.000000,71.825000,55.900000,27.200000,84.400000,6.900000,112.925000
max,3000.000000,172.100000,182.600000,200.000000,38.800000,100.000000,8.470000,291.700000

In [38]:
x=df.select_dtypes(include=['int64','float64']).drop(columns=['Sample_ID'])

In [39]:
y=df['Crop']

In [40]:
model=KNeighborsClassifier(n_neighbors=5)

In [41]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [42]:
model.fit(x_train,y_train)

KNeighborsClassifier()

In [43]:
ypred=model.predict(x_test)

In [44]:
p=precision_score(y_test,ypred,average='macro')
re=recall_score(y_test,ypred,average='macro')
f=f1_score(y_test,ypred,average='macro')
acc=accuracy_score(y_test,ypred)

print(f"Precision: {p:.4f}")
print(f"Recall:    {re:.4f}")
print(f"F1 Score:  {f:.4f}")
print(f"Accuracy:  {acc:.4f}")

Precision: 0.9713
Recall:    0.9703
F1 Score:  0.9707
Accuracy:  0.9700

In [55]:
#user input
n=float(input('Enter Nitrogen value: '))
p=float(input('Enter Phosphorus value: '))
k=float(input('Enter potassium value: '))
temp=float(input('Enter temperature value: '))
humidity=float(input('Enter humidity value: '))
ph=float(input('Enter ph value: '))
rainfall=float(input('Enter rainfall value: '))
predicts=model.predict([[n,p,k,temp,humidity,ph,rainfall]])[0]
print(predicts)

Enter Nitrogen value: 100
Enter Phosphorus value: 82
Enter potassium value: 80
Enter temperature value: 27
Enter humidity value: 78
Enter ph value: 6.2
Enter rainfall value: 110
banana

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(