In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix

In [5]:
df=pd.read_csv("/content/loan_approval.csv")
df

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False
...,...,...,...,...,...,...,...,...
1995,James Schaefer,Robertton,92163,770,12251,13,85.0,True
1996,Diana Lin,New Frank,38799,635,48259,17,40.0,False
1997,Brandon Meyer,East Haley,41957,763,16752,5,60.0,True
1998,Jason Price,Adamland,139022,360,24031,35,55.0,False
1999,Nicole Brown,New Nathantown,41188,482,31397,6,20.0,False

In [7]:
df.head()

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False

In [8]:
df.tail()

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
1995,James Schaefer,Robertton,92163,770,12251,13,85.0,True
1996,Diana Lin,New Frank,38799,635,48259,17,40.0,False
1997,Brandon Meyer,East Haley,41957,763,16752,5,60.0,True
1998,Jason Price,Adamland,139022,360,24031,35,55.0,False
1999,Nicole Brown,New Nathantown,41188,482,31397,6,20.0,False

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            2000 non-null   object
 1   city            2000 non-null   object
 2   income          2000 non-null   int64
 3   credit_score    2000 non-null   int64
 4   loan_amount     2000 non-null   int64
 5   years_employed  2000 non-null   int64
 6   points          2000 non-null   float64
 7   loan_approved   2000 non-null   bool
dtypes: bool(1), float64(1), int64(4), object(2)
memory usage: 111.5+ KB

In [11]:
df.describe()

              income  credit_score   loan_amount  years_employed       points
count    2000.000000   2000.000000   2000.000000     2000.000000  2000.000000
mean    90585.977000    573.946000  25308.503000       20.441000    56.680000
std     34487.874907    160.564945  14207.320147       11.777813    18.638033
min     30053.000000    300.000000   1022.000000        0.000000    10.000000
25%     61296.250000    433.000000  12748.750000       10.000000    45.000000
50%     90387.500000    576.000000  25661.500000       21.000000    55.000000
75%    120099.750000    715.000000  37380.500000       31.000000    70.000000
max    149964.000000    850.000000  49999.000000       40.000000   100.000000

In [12]:
df.isnull().sum()

name              0
city              0
income            0
credit_score      0
loan_amount       0
years_employed    0
points            0
loan_approved     0
dtype: int64

In [20]:
xk=["income","loan_amount","years_employed","credit_score"]
x=df[xk]
y=df["loan_approved"]
print(x)
print(y)

      income  loan_amount  years_employed  credit_score
0     113810        39698              27           389
1      44592        15446              28           729
2      33278        11189              13           584
3     127196        48823              29           344
4      66048        47174               4           496
...      ...          ...             ...           ...
1995   92163        12251              13           770
1996   38799        48259              17           635
1997   41957        16752               5           763
1998  139022        24031              35           360
1999   41188        31397               6           482

[2000 rows x 4 columns]
[False False False ...  True False False]

In [15]:
m=LogisticRegression()
m.fit(x,y)

LogisticRegression()

In [19]:

acc=accuracy_score(y,m.predict(x))
print("Accuracy Score:",acc)

# prediction=m.predict()

# print()

Accuracy Score: 0.9055

In [23]:
df['loan_approved']=df['loan_approved'].map({False:0,True:1})

In [24]:
y=df['loan_approved']
x=df[xk]

In [40]:
a=int(input("Enter Income:"))
b=int(input("Enter Loan Amount:"))
c=int(input("Enter Years Employed:"))
d=int(input("Enter Credit Score:"))
userdata=pd.DataFrame({'income':[a],
                       'loan_amount':[b],
                       'years_employed':[c],
                       'credit_score':[d]})
print(userdata)
predict=m.predict(userdata)
if predict==0:
  print("loan Not approved")
else:
  print("loan approved")

Enter Income:5000
Enter Loan Amount:40000
Enter Years Employed:4
Enter Credit Score:900
   income  loan_amount  years_employed  credit_score
0    5000        40000               4           900
loan approved