In [1]:
import pandas as np
import requests
from bs4 import BeautifulSoup

In [2]:
url="https://books.toscrape.com"

In [3]:
req=requests.get(url)

In [4]:
print('status code:',req.status_code)

status code: 200

In [12]:
#html to text ----beautifulsoup
soup=BeautifulSoup(req.text,'html.parser')


book=soup.select_one('article.product_pod h3 a')

price=soup.select_one('article.product_pod p.price_color')

print(book.text)
print(price.text)

A Light in the ...
Â£51.77

In [18]:
availability=soup.select_one('p.instock.availability')
print(availability.text.strip())

In stock

In [20]:
####stor as key values like dict
bookdetails={'title':book['title'],
             'price':price.text,
             'availability':availability.text.strip()}
print(bookdetails)

{'title': 'A Light in the Attic', 'price': 'Â£51.77', 'availability': 'In stock'}

In [21]:
print("book details:")
for key,value in bookdetails.items():
  print(f'{key}:{value}')

book details:
title:A Light in the Attic
price:Â£51.77
availability:In stock

In [24]:
df=np.DataFrame([bookdetails])
df

                  title    price availability
0  A Light in the Attic  Â£51.77     In stock

In [31]:
csvconvert=df.to_csv('Mohanrajbookscraping.csv',index=False)

In [30]:
xlconvert=df.to_excel("Mohanrajbookscraping.xlsx",index=False)

In [32]:
from google.colab import files

In [33]:
files.download('Mohanrajbookscraping.csv')

In [34]:
files.download('Mohanrajbookscraping.xlsx')

In [39]:
bo=[]


for item in soup.select('article.product_pod'):
  title=item.select_one('h3 a')['title']
  price=item.select_one('p.price_color').text
  availability=item.select_one('p.instock.availability').text.strip()
  rating=item.select_one('.star-rating')['class'][1]
  book={'title':title,
        'price':price,
        'availability':availability,
        'rating':rating}
  bo.append(book)

In [41]:
df1=np.DataFrame(bo)
df1

,title,price,availability,rating
0,A Light in the Attic,Â£51.77,In stock,Three
1,Tipping the Velvet,Â£53.74,In stock,One
2,Soumission,Â£50.10,In stock,One
3,Sharp Objects,Â£47.82,In stock,Four
4,Sapiens: A Brief History of Humankind,Â£54.23,In stock,Five
5,The Requiem Red,Â£22.65,In stock,One
6,The Dirty Little Secrets of Getting Your Dream...,Â£33.34,In stock,Four
7,The Coming Woman: A Novel Based on the Life of...,Â£17.93,In stock,Three
8,The Boys in the Boat: Nine Americans and Their...,Â£22.60,In stock,Four
9,The Black Maria,Â£52.15,In stock,One
10,"Starving Hearts (Triangular Trade Trilogy, #1)",Â£13.99,In stock,Two
11,Shakespeare's Sonnets,Â£20.66,In stock,Four
12,Set Me Free,Â£17.46,In stock,Five
13,Scott Pilgrim's Precious Little Life (Scott Pi...,Â£52.29,In stock,Five
14,Rip it Up and Start Again,Â£35.02,In stock,Five
15,Our Band Could Be Your Life: Scenes from the A...,Â£57.25,In stock,Three
16,Olio,Â£23.88,In stock,One
17,Mesaerion: The Best Science Fiction Stories 18...,Â£37.59,In stock,One
18,Libertarianism for Beginners,Â£51.33,In stock,Two
19,It's Only the Himalayas,Â£45.17,In stock,Two

In [45]:
cv=df.to_csv('mohanraj csv creation.csv')
xl=df.to_excel('mohanraj excel creation.xlsx')

In [47]:
files.download('mohanraj csv creation.csv')
files.download('mohanraj excel creation.xlsx')